### PR TITLE
Eslint migration

### PR DESCRIPTION
**Pull request by stephensli**
# Eslint Upgrade  #287 

This pull request focuses on the migration from `semistandard` to `eslint` with `standard/standard` as the direct rule set for linting the application. By moving to `eslint` allows future development and migration to Typescript smoother. While also supporting linting, code style enforcement, and support of locating errors.

eslint: https://eslint.org/

### Linted Content

Linting has been run throughout the application which has mainly shifted `var` to `const` and `var` to `let` where applicable. While also correcting string index references to direct references e.g a['test'] to a.test.

### Node V8 Support (Breaking Change)

Development of the project will no longer support Node version 8 due to `eslint` using unsupported JavaScript features. Node V8 is also currently deprecated since `2019-12-31` and this should not be seen as a negative breaking change.

### CODE REVIEW

**Review by cameel — CHANGES_REQUESTED** [review]
The changes look fine to me. The only thing to settle is the node.js v8 support.

Personally, I think it's fine drop it - even v10 is already EOL and the major Solidity frameworks that depend on solc-js already require v12+ themselves. I'd like to get an ack from @chriseth and/or @axic before we go forward with it though.

Also, if we're dropping it, please adjust [`.circleci/config.yml`](https://github.com/ethereum/solc-js/blob/master/.circleci/config.yml) to remove the job that runs on that version. I'd remove the disabled v4 and v6 as well. And I'd also add a comment explaining that ESLint is the reason behind the v10+ requirement.

**Review by cameel — APPROVED** [review]
I'm marking it as approved since I don't see any problem with dropping v8 and I suspect that @chriseth and @axic will agree. We still need to wait for their approval though - especially because the `node-v8` job is marked as a required check and I don't have permissions to remove it from repo settings myself.

I think you can already safely rebase your other PR on this one though.

**Comment by cameel** [comment]
https://github.com/ethereum/solc-js/pull/566#issuecomment-988990187 was actually meant to go here:

> I asked @axic about the PR on the call today. He's going to take a look but one problem he pointed out already is that removal of v8 support is technically a breaking change unfortunately.
>
> Well, maybe we could make a breaking 0.9.x release early?

**Comment by cameel** [comment]
@axic Reposting this from the chat so that it does not get lost:

This is what I managed to find so far for [projects we have listed in #10278](https://github.com/ethereum/solidity/issues/10278#issuecomment-730451252)
- Waffle: >= v10 or lower (https://github.com/EthWorks/Waffle/issues/28#issuecomment-454737193))
- Truffle: >= v12 (https://github.com/trufflesuite/truffle/issues/4135)
- Hardhat: >= v12 (https://github.com/nomiclabs/hardhat/pull/1760)
- Embark: ???
- Saddle: probably still >= 10, might be lower (https://github.com/compound-finance/saddle/pull/4)

https://en.wikipedia.org/wiki/Node.js#Releases
```
 8.x    End-of-Life      Carbon       2017-05-30   2019-12-31
 9.x    End-of-Life                   2017-10-01   2018-06-30
10.x    End-of-Life      Dubnium      2018-04-24   2021-04-30
11.x    End-of-Life                   2018-10-23   2019-06-01
12.x    Maintenance LTS  Erbium       2019-04-23   2022-04-30
13.x    End-of-Life                   2019-10-22   2020-06-01
14.x    Active LTS       Fermium      2020-04-21   2023-04-30
15.x    End of Life                   2020-10-20   2021-06-01
16.x    Active LTS       Gallium      2021-04-20   2024-04-30
17.x    Current                       2021-10-19   2022-06-01
18.x    Planned                       2022-04-19   2025-04-30 
```

**Comment by cameel** [comment]
@chriseth approved dropping v8 support. This should now be rebased on #572.

**Comment by stephensli** [comment]
@cameel done

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
Why did this miss a bunch of other issues, like single-quotes vs double-quotes, missing semicolons, spacing around function names and object, etc. ?

cc @stephensli @cameel

**Comment by stephensli** [comment]
@axic you are going to have to provide examples,  a quick fly over is all good.

The only file that was not linted was: solcjs due to the extension not existing. #566 makes this change.

**Comment by axic** [comment]
`solcjs` as you mentioned due to the filename issue, but also `test/compiler.js`.

**Pull request merged**
