### PR TITLE
PR48: Add support to download custom compiler and use it from solcjs cli

### PR DESCRIPTION
**Pull request by chevdor**
See #48 This is the same, just put in a separate branch.

### CODE REVIEW

**Comment by chevdor** [comment]
Should be merged before #56

**Comment by axic** [comment]
@chevdor so we should start with splitting up this PR. Let me know if you would have time for a quick chat on Gitter

**Comment by axic** [comment]
We could start with creating PRs for (one for each item below):
- fix for #22
- fix for #51

**Comment by chevdor** [comment]
#22 isolated in PR #61

**Comment by chevdor** [comment]
#51 isolated in #62

**Comment by chevdor** [comment]
Rebased version of this PR without #22 and #51 in #63

**Pull request closed without merging**
