### PR TITLE
Catch & rethrow exception so the function pointer can be freed

### PR DESCRIPTION
**Pull request by axic**
Aims to fix https://github.com/ethereum/browser-solidity/issues/212

### CODE REVIEW

**Comment by chriseth** [comment]
What about adding / removing the function only when a new compiler version is loaded / unloaded? We can assign the callback to a variable available to the wrapper shortly before we call compileInternal.

**Comment by chriseth** [comment]
CI failures due to style problem

**Comment by axic** [comment]
> CI failures due to style problem

Fixed.

**Comment by axic** [comment]
> What about adding / removing the function only when a new compiler version is loaded / unloaded? 

The only drawback is the need of a `cleanup()` method which needs to be called by the user. Also somehow in the case of multithreading it can cause issues.

**Comment by chriseth** [comment]
Checked it out and wanted to fix it in the same second :-)

**Pull request merged**
