### PR TITLE
Use outputSelection in jsonio tests

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
@chriseth can this be merged?

**Comment by chriseth** [comment]
Wouldn't it be better to request everything in most tests and only have some test that only request the bytecode?

**Comment by axic** [comment]
I had `'*'` before but that is not included in the docs (yet) and all the tests only care about `evm.bytecode` so I've figured the tests will be faster this way (once implemented properly).

**Comment by chriseth** [comment]
ok sure, but do we at least have tests that request everything?

**Comment by axic** [comment]
Not here, we have them in Solidity.

**Pull request merged**
