### PR TITLE
Wrapper should expose its helpers even if not loading soljson

### PR DESCRIPTION
**Pull request by yann300**
allow loading wrapper without any preloaded compiler

### CODE REVIEW

**Comment by chriseth** [comment]
This looks to me more like "force loading without compiler"

**Comment by axic** [comment]
@yann300 as mentioned I had a different way of solving this.

Can you explain your actual use case?

**Comment by yann300** [comment]
the compiler is used by remix's tests:
I want to be able to call `loadRemoteVersion()` version without having to specify a preloaded solc.js.
now `solcWrapper()` will throw.

`
var solcWrapper = require('solc/wrapper')

solcWrapper().loadRemoteVersion('latest', function (err, compiler) {
    if (err) {
      t.fail(err)
    } else {
      test(t, compiler)
    }
  })`

**Comment by axic** [comment]
@yann300 thanks, that matches one of my motivations. I'll look into this today.

**Comment by chriseth** [comment]
@yann300 @axic is this still needed?

**Comment by axic** [comment]
I don't think this is needed since wrapper can be loaded independently. @yann300 please let us know and we can reopen.

**Pull request closed without merging**
