### PR TITLE
Lint consistency fixes

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
@stephensli can you also check this? It pulls in a lot of the remaining lint fixes.

**Comment by stephensli** [comment]
@axic  LGTM - Not sure how the test/compiler did not get fully linted, the solcjs was not auto-linted due to the file not having a extension.

**Review by stephensli — APPROVED** [review]

**Comment by axic** [comment]
> the solcjs was not auto-linted due to the file not having a extension

Oh, good insight.

**Comment by cameel** [comment]
So has this been replaced by #587? Or was #587 just a part of it?

**Comment by axic** [comment]
Mostly superseded by #587. There is one set of opinionated changes in #566 which I could move here.

**Pull request closed without merging**
