### PR TITLE
Version 0.4.26

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by blitz-1306** [comment]
Hello, @chriseth. Just curious: this would be merged any time soon?

**Comment by chriseth** [comment]
Yeah good question. It has been superseded by more recent versions. As far as I know, npm only records the latest version. It could be merged in a way where the merge commit basically undoes the change here, so that the commit is at least an ancestor of HEAD... Do you have any other suggestions?

**Comment by blitz-1306** [comment]
Have you considered using https://stackoverflow.com/a/27665031/2269749 ?

**Comment by chriseth** [comment]
Ah, so you are saying the problem is that the version is not published on NPM (and not that this branch is not merged)?

**Comment by chriseth** [comment]
Thanks for the hint, just published it!

**Comment by blitz-1306** [comment]
@chriseth You mentioned:
> As far as I know, npm only records the latest version.
That is why I suggested to consider tags. Also, I'm interested in Solc release of 0.4.26, which is not currently present in SolcJs. One of my projects allows to run solidity legacy versions.

You're welcome.

**Comment by chriseth** [comment]
So is this problem fixed for you?

**Comment by blitz-1306** [comment]
@chriseth yeah, sure.

**Comment by chriseth** [comment]
Ok, great!

**Comment by axic** [comment]
@chriseth I usually push the tags to this repo, but it hasn't been done since February.

Did you push this PR as the old version? If so, we should just tag this commit hash 0.4.26 and close the PR.

**Comment by chriseth** [comment]
Yes, the npm packages was published from this commit. Can you push the tags, please? Also, could you update the solidity release checklist to include that step? Thanks!

**Comment by axic** [comment]
Pushed all the missing tags.

**Comment by chriseth** [comment]
Thanks!

**Pull request closed without merging**
