### PR TITLE
Move CI To Circleci

### LINKED ISSUE #211: Move CI to circleci
Currently solc-js is using travis to run tests:
- `npm run test`
- `npm run coveralls`

It runs these on all stable node.js releases: 4, 6, 8 (should also do on nodejs 10)

The goal is to write a circleci configuration doing the same.

### PR DESCRIPTION
**Pull request by bakaoh**
Fix #211

### CODE REVIEW

**Comment by axic** [comment]
@chriseth I think this looks good, but circleci needs to be enabled first.

**Comment by chriseth** [comment]
You mean I should do it?

**Comment by chriseth** [comment]
Not sure, I think it just has to be merged.

**Comment by chriseth** [comment]
Rebased.

**Comment by axic** [comment]
> You mean I should do it?

Yeah the setting on circleci doesn't show up for me.

**Comment by axic** [comment]
Albeit we've merged this, it turns out the coveralls part is not working yet. Also the badge wasn't added to the README. 

@bakaoh would you mind creating a PR adding a badge to the README?

**Comment by bakaoh** [comment]
@axic --- i added the badge to the Readme
For coveralls to working with circleci, you need to add your repo token to it (i can't get your token so i can't help here, but it's pretty simple https://docs.coveralls.io/supported-ci-services)

**Comment by axic** [comment]
> For coveralls to working with circleci, you need to add your repo token to it (i can't get your token so i can't help here, but it's pretty simple https://docs.coveralls.io/supported-ci-services)

Thanks for the pointers, will look into it.

**Pull request merged**
