### PR TITLE
Set version to 0.4.25.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by axic** [comment]
I think this must branch off the last release tag.

**Comment by chriseth** [comment]
I don't really understand what you mean. Why can't it just be a commit on top of current master?

**Comment by chriseth** [comment]
Ok, understood now. Any argument against just running `num publish` from this branch and then merging afterwards?

**Comment by axic** [comment]
I think better if you branch off the tag `0.4.24` locally, apply and commit the version change, publish, tag it and push the tag. Pushing the tag will push the commit you made.

**Comment by chriseth** [comment]
I did branch off the v0.4.24 branch now, but I guess we should also eventually merge this branch into master shouldn't we?

**Comment by chriseth** [comment]
This is weird, why can't I merge this into master? Github is asking me to merge master into this first. `version0425` is not chuck norris, is it?

**Pull request merged**
