### PR TITLE
Refactor downloadCurrentVersion.js with Promises

### PR DESCRIPTION
**Pull request by watilde**
This patch can be about one's preference so I'd like to hear your opinion on using Promise/modern ways.

##### Summary
+ Replace a regex with `semver.clean`
+ Replace callback processes with Promise

### CODE REVIEW

**Comment by watilde** [comment]
The ci error is about this issue: https://travis-ci.org/watilde/solc-js/jobs/281783531#L442. I'm asking to travis people now.

**Comment by axic** [comment]
@watilde I see you're removing `memory-stream`. Any reason not to use it?

**Comment by watilde** [comment]
Not really, but it worked with enough speed. I can rever the commit to keep using `memory-stream`, but the upstream seems to be updated updated already so I will close this PR for now. Thanks!

**Comment by axic** [comment]
@watilde we haven't merged any feature like this, can you push it back?

**Comment by watilde** [comment]
@axic Sure, I'd love to. I will make another pull request to rebase this patch on top of master branch.

**Pull request closed without merging**
