### PR TITLE
Add the missing `common/helpers.ts` to `package.json`

### LINKED ISSUE #622: `Uncaught Error: Cannot find module './common/helpers'` on 0.8.14
Looks like the helpers added in #603 were not added to the package so trying to import it fails:
```bash
npm install solc@0.8.14
node_modules/solc/solc.js --version
```
```
Error: Cannot find module './common/helpers'
```
Also:
```bash
node -e 'require("solc")'
```
```
Error: Cannot find module './common/helpers'
```

Also, we need to investigate why this didn't fail any tests. We specifically build the package in CI and install it and that test should have caught it.

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #622.

I guess this is enough to fix the issue, but maybe better if @cameel and/or @stephensli confirmed.

### CODE REVIEW

**Comment by stephensli** [comment]
@cameel this will do it, please just do a npm build-tarball and check the tarball output to see if the content contains everything required. If anything else is missing (hopefully not) include it in this PR @ekpyron

**Review by chriseth — APPROVED** [review]

**Comment by nataouze** [comment]
Looks like "common/types.js" should be added too as it is also imported in linker.ts

**Comment by ekpyron** [comment]
As far as I can see ``dist/common/types.js`` (i.e. the js file built from ``common/types.ts``), is empty and not imported by any of the other built js files - probably since it's only relevant for typescript and does not carry over to js...

**Comment by nataouze** [comment]
Yes you are right, it is not present in the built linker.js file. Thank you

**Comment by stephensli** [comment]
@cameel I would not invest much effort as #614 updates the exported files.

**Comment by cameel** [comment]
Well, we still need to find out why it went through our tests unnoticed. And then, when we fix the tests, we should rebase this PR on top of that to make sure the fix still passes them. I hope that the missing entry in `package.json` is the only problem but we really can't be sure of anything until tests are working properly.

**Pull request merged**
