### PR TITLE
Move from semistandard to standard

### PR DESCRIPTION
**Pull request by watilde**
##### Summary
+ `npm i --save-dev standard`
+ `npm rm --save-dev semistandard`
+ Use standard and fix the errors
+ Lint check at solcjs and fix the errors

Fixes https://github.com/ethereum/solc-js/issues/66.

### CODE REVIEW

**Comment by watilde** [comment]
The ci error is not related to this PR.

**Comment by axic** [comment]
Thanks. This is long planned, but we wanted to merge the pending pull requests first given it would be a lot of work otherwise.

**Comment by watilde** [comment]
@axic That makes sense to not make the commit conflicts. Could I possibly support you to push the pending patches forward by somehow?

**Comment by axic** [comment]
@watilde that would be very nice! The stdin issue is priority now, but after that #61, #63, #64 should be split into separate PRs per feature. They are useful, but hard to deal with in their current shape.

**Comment by watilde** [comment]
I will close this since upstream was updated already and it's not the time to move to standard for now. Thanks!

**Pull request closed without merging**
